/* Application.c generated by valac 0.50.5, the Vala compiler
 * generated from Application.vala, do not modify */

/*
* Copyright (c) 2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*
*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <adwaita.h>
#include <glib.h>
#include "config.h"
#include <stdlib.h>
#include <string.h>
#include <locale.h>
#include <glib/gi18n-lib.h>

#define DOT_MATRIX_TYPE_APPLICATION (dot_matrix_application_get_type ())
#define DOT_MATRIX_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOT_MATRIX_TYPE_APPLICATION, DotMatrixApplication))
#define DOT_MATRIX_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOT_MATRIX_TYPE_APPLICATION, DotMatrixApplicationClass))
#define DOT_MATRIX_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOT_MATRIX_TYPE_APPLICATION))
#define DOT_MATRIX_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOT_MATRIX_TYPE_APPLICATION))
#define DOT_MATRIX_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOT_MATRIX_TYPE_APPLICATION, DotMatrixApplicationClass))

typedef struct _DotMatrixApplication DotMatrixApplication;
typedef struct _DotMatrixApplicationClass DotMatrixApplicationClass;
typedef struct _DotMatrixApplicationPrivate DotMatrixApplicationPrivate;
enum  {
	DOT_MATRIX_APPLICATION_0_PROPERTY,
	DOT_MATRIX_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* dot_matrix_application_properties[DOT_MATRIX_APPLICATION_NUM_PROPERTIES];

#define DOT_MATRIX_TYPE_MAIN_WINDOW (dot_matrix_main_window_get_type ())
#define DOT_MATRIX_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindow))
#define DOT_MATRIX_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindowClass))
#define DOT_MATRIX_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOT_MATRIX_TYPE_MAIN_WINDOW))
#define DOT_MATRIX_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOT_MATRIX_TYPE_MAIN_WINDOW))
#define DOT_MATRIX_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindowClass))

typedef struct _DotMatrixMainWindow DotMatrixMainWindow;
typedef struct _DotMatrixMainWindowClass DotMatrixMainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _DotMatrixApplication {
	GtkApplication parent_instance;
	DotMatrixApplicationPrivate * priv;
};

struct _DotMatrixApplicationClass {
	GtkApplicationClass parent_class;
};

static gpointer dot_matrix_application_parent_class = NULL;
extern DotMatrixMainWindow* dot_matrix_application_win;
DotMatrixMainWindow* dot_matrix_application_win = NULL;
extern GSettings* dot_matrix_application_gsettings;
GSettings* dot_matrix_application_gsettings = NULL;

GType dot_matrix_application_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DotMatrixApplication, g_object_unref)
GType dot_matrix_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DotMatrixMainWindow, g_object_unref)
DotMatrixApplication* dot_matrix_application_new (void);
DotMatrixApplication* dot_matrix_application_construct (GType object_type);
static void dot_matrix_application_real_activate (GApplication* base);
DotMatrixMainWindow* dot_matrix_main_window_new (GtkApplication* application);
DotMatrixMainWindow* dot_matrix_main_window_construct (GType object_type,
                                                       GtkApplication* application);
gint dot_matrix_application_main (gchar** args,
                                  gint args_length1);
static GObject * dot_matrix_application_constructor (GType type,
                                              guint n_construct_properties,
                                              GObjectConstructParam * construct_properties);
static void dot_matrix_application_finalize (GObject * obj);
static GType dot_matrix_application_get_type_once (void);

DotMatrixApplication*
dot_matrix_application_construct (GType object_type)
{
	DotMatrixApplication * self = NULL;
#line 26 "../src/Application.vala"
	self = (DotMatrixApplication*) g_object_new (object_type, "flags", G_APPLICATION_FLAGS_NONE, "application-id", APP_ID, NULL);
#line 25 "../src/Application.vala"
	return self;
#line 104 "Application.c"
}

DotMatrixApplication*
dot_matrix_application_new (void)
{
#line 25 "../src/Application.vala"
	return dot_matrix_application_construct (DOT_MATRIX_TYPE_APPLICATION);
#line 112 "Application.c"
}

static void
dot_matrix_application_real_activate (GApplication* base)
{
	DotMatrixApplication * self;
	DotMatrixMainWindow* _tmp0_;
	DotMatrixMainWindow* _tmp2_;
#line 41 "../src/Application.vala"
	self = (DotMatrixApplication*) base;
#line 42 "../src/Application.vala"
	_tmp0_ = dot_matrix_application_win;
#line 42 "../src/Application.vala"
	if (_tmp0_ != NULL) {
#line 127 "Application.c"
		DotMatrixMainWindow* _tmp1_;
#line 43 "../src/Application.vala"
		_tmp1_ = dot_matrix_application_win;
#line 43 "../src/Application.vala"
		gtk_window_present ((GtkWindow*) _tmp1_);
#line 44 "../src/Application.vala"
		return;
#line 135 "Application.c"
	}
#line 46 "../src/Application.vala"
	_tmp2_ = dot_matrix_main_window_new ((GtkApplication*) self);
#line 46 "../src/Application.vala"
	g_object_ref_sink (_tmp2_);
#line 46 "../src/Application.vala"
	_g_object_unref0 (dot_matrix_application_win);
#line 46 "../src/Application.vala"
	dot_matrix_application_win = _tmp2_;
#line 145 "Application.c"
}

gint
dot_matrix_application_main (gchar** args,
                             gint args_length1)
{
	DotMatrixApplication* app = NULL;
	DotMatrixApplication* _tmp0_;
	gint result = 0;
#line 49 "../src/Application.vala"
	_tmp0_ = dot_matrix_application_new ();
#line 49 "../src/Application.vala"
	app = _tmp0_;
#line 50 "../src/Application.vala"
	result = g_application_run ((GApplication*) app, (gint) args_length1, args);
#line 50 "../src/Application.vala"
	_g_object_unref0 (app);
#line 50 "../src/Application.vala"
	return result;
#line 165 "Application.c"
}

int
main (int argc,
      char ** argv)
{
#line 48 "../src/Application.vala"
	return dot_matrix_application_main (argv, argc);
#line 174 "Application.c"
}

static GObject *
dot_matrix_application_constructor (GType type,
                                    guint n_construct_properties,
                                    GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	DotMatrixApplication * self;
#line 35 "../src/Application.vala"
	parent_class = G_OBJECT_CLASS (dot_matrix_application_parent_class);
#line 35 "../src/Application.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 35 "../src/Application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DOT_MATRIX_TYPE_APPLICATION, DotMatrixApplication);
#line 36 "../src/Application.vala"
	setlocale (LC_ALL, "");
#line 37 "../src/Application.vala"
	bindtextdomain (GETTEXT_PACKAGE, GNOMELOCALEDIR);
#line 38 "../src/Application.vala"
	textdomain (GETTEXT_PACKAGE);
#line 35 "../src/Application.vala"
	return obj;
#line 199 "Application.c"
}

static void
dot_matrix_application_class_init (DotMatrixApplicationClass * klass,
                                   gpointer klass_data)
{
	GSettings* _tmp0_;
#line 21 "../src/Application.vala"
	dot_matrix_application_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/Application.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) dot_matrix_application_real_activate;
#line 21 "../src/Application.vala"
	G_OBJECT_CLASS (klass)->constructor = dot_matrix_application_constructor;
#line 21 "../src/Application.vala"
	G_OBJECT_CLASS (klass)->finalize = dot_matrix_application_finalize;
#line 32 "../src/Application.vala"
	_tmp0_ = g_settings_new ("io.github.lainsce.DotMatrix");
#line 32 "../src/Application.vala"
	_g_object_unref0 (dot_matrix_application_gsettings);
#line 32 "../src/Application.vala"
	dot_matrix_application_gsettings = _tmp0_;
#line 221 "Application.c"
}

static void
dot_matrix_application_instance_init (DotMatrixApplication * self,
                                      gpointer klass)
{
}

static void
dot_matrix_application_finalize (GObject * obj)
{
	DotMatrixApplication * self;
#line 21 "../src/Application.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DOT_MATRIX_TYPE_APPLICATION, DotMatrixApplication);
#line 21 "../src/Application.vala"
	G_OBJECT_CLASS (dot_matrix_application_parent_class)->finalize (obj);
#line 238 "Application.c"
}

static GType
dot_matrix_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DotMatrixApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dot_matrix_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DotMatrixApplication), 0, (GInstanceInitFunc) dot_matrix_application_instance_init, NULL };
	GType dot_matrix_application_type_id;
	dot_matrix_application_type_id = g_type_register_static (gtk_application_get_type (), "DotMatrixApplication", &g_define_type_info, 0);
	return dot_matrix_application_type_id;
}

GType
dot_matrix_application_get_type (void)
{
	static volatile gsize dot_matrix_application_type_id__volatile = 0;
	if (g_once_init_enter (&dot_matrix_application_type_id__volatile)) {
		GType dot_matrix_application_type_id;
		dot_matrix_application_type_id = dot_matrix_application_get_type_once ();
		g_once_init_leave (&dot_matrix_application_type_id__volatile, dot_matrix_application_type_id);
	}
	return dot_matrix_application_type_id__volatile;
}

