/* MainWindow.c generated by valac 0.50.5, the Vala compiler
 * generated from MainWindow.vala, do not modify */

/*
* Copyright (c) 2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <adwaita.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <gee.h>
#include "config.h"
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>

#define DOT_MATRIX_TYPE_MAIN_WINDOW (dot_matrix_main_window_get_type ())
#define DOT_MATRIX_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindow))
#define DOT_MATRIX_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindowClass))
#define DOT_MATRIX_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOT_MATRIX_TYPE_MAIN_WINDOW))
#define DOT_MATRIX_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOT_MATRIX_TYPE_MAIN_WINDOW))
#define DOT_MATRIX_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindowClass))

typedef struct _DotMatrixMainWindow DotMatrixMainWindow;
typedef struct _DotMatrixMainWindowClass DotMatrixMainWindowClass;
typedef struct _DotMatrixMainWindowPrivate DotMatrixMainWindowPrivate;

#define DOT_MATRIX_WIDGETS_TYPE_UI (dot_matrix_widgets_ui_get_type ())
#define DOT_MATRIX_WIDGETS_UI(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOT_MATRIX_WIDGETS_TYPE_UI, DotMatrixWidgetsUI))
#define DOT_MATRIX_WIDGETS_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOT_MATRIX_WIDGETS_TYPE_UI, DotMatrixWidgetsUIClass))
#define DOT_MATRIX_WIDGETS_IS_UI(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOT_MATRIX_WIDGETS_TYPE_UI))
#define DOT_MATRIX_WIDGETS_IS_UI_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOT_MATRIX_WIDGETS_TYPE_UI))
#define DOT_MATRIX_WIDGETS_UI_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOT_MATRIX_WIDGETS_TYPE_UI, DotMatrixWidgetsUIClass))

typedef struct _DotMatrixWidgetsUI DotMatrixWidgetsUI;
typedef struct _DotMatrixWidgetsUIClass DotMatrixWidgetsUIClass;
enum  {
	DOT_MATRIX_MAIN_WINDOW_0_PROPERTY,
	DOT_MATRIX_MAIN_WINDOW_ACTIONS_PROPERTY,
	DOT_MATRIX_MAIN_WINDOW_APP_PROPERTY,
	DOT_MATRIX_MAIN_WINDOW_NUM_PROPERTIES
};
static GParamSpec* dot_matrix_main_window_properties[DOT_MATRIX_MAIN_WINDOW_NUM_PROPERTIES];
#define _dot_matrix_widgets_ui_unref0(var) ((var == NULL) ? NULL : (var = (dot_matrix_widgets_ui_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef void (*DotMatrixMainWindowHookFunc) (gpointer user_data);

#define DOT_MATRIX_TYPE_PATH (dot_matrix_path_get_type ())
#define DOT_MATRIX_PATH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOT_MATRIX_TYPE_PATH, DotMatrixPath))
#define DOT_MATRIX_PATH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOT_MATRIX_TYPE_PATH, DotMatrixPathClass))
#define DOT_MATRIX_IS_PATH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOT_MATRIX_TYPE_PATH))
#define DOT_MATRIX_IS_PATH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOT_MATRIX_TYPE_PATH))
#define DOT_MATRIX_PATH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOT_MATRIX_TYPE_PATH, DotMatrixPathClass))

typedef struct _DotMatrixPath DotMatrixPath;
typedef struct _DotMatrixPathClass DotMatrixPathClass;
typedef struct _DotMatrixWidgetsUIPrivate DotMatrixWidgetsUIPrivate;
#define _dot_matrix_path_unref0(var) ((var == NULL) ? NULL : (var = (dot_matrix_path_unref (var), NULL)))
typedef struct _DotMatrixPathPrivate DotMatrixPathPrivate;

#define DOT_MATRIX_TYPE_POINT (dot_matrix_point_get_type ())
#define DOT_MATRIX_POINT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DOT_MATRIX_TYPE_POINT, DotMatrixPoint))
#define DOT_MATRIX_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DOT_MATRIX_TYPE_POINT, DotMatrixPointClass))
#define DOT_MATRIX_IS_POINT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DOT_MATRIX_TYPE_POINT))
#define DOT_MATRIX_IS_POINT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DOT_MATRIX_TYPE_POINT))
#define DOT_MATRIX_POINT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DOT_MATRIX_TYPE_POINT, DotMatrixPointClass))

typedef struct _DotMatrixPoint DotMatrixPoint;
typedef struct _DotMatrixPointClass DotMatrixPointClass;

struct _DotMatrixMainWindow {
	AdwApplicationWindow parent_instance;
	DotMatrixMainWindowPrivate * priv;
	DotMatrixWidgetsUI* ui;
	GtkButton* new_button;
	GtkButton* save_button;
	GtkButton* undo_button;
	GtkMenuButton* menu_button;
	GtkDrawingArea* da;
	GtkColorButton* line_color_button;
	GtkSpinButton* line_thickness_button;
	GtkButton* line_curve_button;
	GtkButton* line_curve_reverse_button;
	GtkButton* line_straight_button;
	GtkButton* close_path_button;
	gchar* background;
	gchar* f_high;
	gchar* f_med;
	gchar* f_low;
	gchar* f_inv;
	gchar* b_high;
	gchar* b_med;
	gchar* b_low;
	gchar* b_inv;
};

struct _DotMatrixMainWindowClass {
	AdwApplicationWindowClass parent_class;
};

struct _DotMatrixMainWindowPrivate {
	GSimpleActionGroup* _actions;
	GtkApplication* _app;
};

struct _DotMatrixWidgetsUI {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DotMatrixWidgetsUIPrivate * priv;
	DotMatrixMainWindow* window;
	GList* paths;
	DotMatrixPath* current_path;
	gdouble line_thickness;
	GdkRGBA grid_main_dot_color;
	GdkRGBA grid_dot_color;
	GdkRGBA background_color;
	GdkRGBA line_color;
	GtkColorButton* line_color_button;
	GtkDrawingArea* da;
};

struct _DotMatrixWidgetsUIClass {
	GTypeClass parent_class;
	void (*finalize) (DotMatrixWidgetsUI *self);
};

struct _DotMatrixPath {
	GTypeInstance parent_instance;
	volatile int ref_count;
	DotMatrixPathPrivate * priv;
	GList* points;
	GdkRGBA color;
};

struct _DotMatrixPathClass {
	GTypeClass parent_class;
	void (*finalize) (DotMatrixPath *self);
};

static gint DotMatrixMainWindow_private_offset;
static gpointer dot_matrix_main_window_parent_class = NULL;
extern GeeMultiMap* dot_matrix_main_window_action_accelerators;
GeeMultiMap* dot_matrix_main_window_action_accelerators = NULL;
extern GSettings* dot_matrix_application_gsettings;

GType dot_matrix_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DotMatrixMainWindow, g_object_unref)
gpointer dot_matrix_widgets_ui_ref (gpointer instance);
void dot_matrix_widgets_ui_unref (gpointer instance);
GParamSpec* dot_matrix_widgets_param_spec_ui (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
void dot_matrix_widgets_value_set_ui (GValue* value,
                                      gpointer v_object);
void dot_matrix_widgets_value_take_ui (GValue* value,
                                       gpointer v_object);
gpointer dot_matrix_widgets_value_get_ui (const GValue* value);
GType dot_matrix_widgets_ui_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DotMatrixWidgetsUI, dot_matrix_widgets_ui_unref)
#define DOT_MATRIX_MAIN_WINDOW_ACTION_PREFIX "win."
#define DOT_MATRIX_MAIN_WINDOW_ACTION_ABOUT "action_about"
#define DOT_MATRIX_MAIN_WINDOW_ACTION_KEYS "action_keys"
void dot_matrix_main_window_action_about (DotMatrixMainWindow* self);
static void _dot_matrix_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                            GVariant* parameter,
                                                                            gpointer self);
void dot_matrix_main_window_action_keys (DotMatrixMainWindow* self);
static void _dot_matrix_main_window_action_keys_gsimple_action_activate_callback (GSimpleAction* action,
                                                                           GVariant* parameter,
                                                                           gpointer self);
DotMatrixMainWindow* dot_matrix_main_window_new (GtkApplication* application);
DotMatrixMainWindow* dot_matrix_main_window_construct (GType object_type,
                                                       GtkApplication* application);
static gboolean dot_matrix_main_window_real_close_request (GtkWindow* base);
gboolean dot_matrix_widgets_ui_get_dirty (DotMatrixWidgetsUI* self);
void dot_matrix_widgets_ui_clear (DotMatrixWidgetsUI* self);
void dot_matrix_main_window_listen_to_changes (DotMatrixMainWindow* self);
GSimpleActionGroup* dot_matrix_main_window_get_actions (DotMatrixMainWindow* self);
static void dot_matrix_main_window_set_actions (DotMatrixMainWindow* self,
                                         GSimpleActionGroup* value);
GtkApplication* dot_matrix_main_window_get_app (DotMatrixMainWindow* self);
static void dot_matrix_main_window_set_app (DotMatrixMainWindow* self,
                                     GtkApplication* value);
static GObject * dot_matrix_main_window_constructor (GType type,
                                              guint n_construct_properties,
                                              GObjectConstructParam * construct_properties);
static void _vala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _dot_matrix_main_window___lambda9_ (DotMatrixMainWindow* self,
                                         GtkButton* e);
static void __dot_matrix_main_window___lambda9__gtk_button_clicked (GtkButton* _sender,
                                                             gpointer self);
static void _dot_matrix_main_window___lambda10_ (DotMatrixMainWindow* self,
                                          GtkButton* e);
void dot_matrix_widgets_ui_save (DotMatrixWidgetsUI* self,
                                 GAsyncReadyCallback _callback_,
                                 gpointer _user_data_);
void dot_matrix_widgets_ui_save_finish (DotMatrixWidgetsUI* self,
                                        GAsyncResult* _res_,
                                        GError** error);
static void __dot_matrix_main_window___lambda10__gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self);
static void _dot_matrix_main_window___lambda11_ (DotMatrixMainWindow* self,
                                          GtkButton* e);
void dot_matrix_widgets_ui_undo (DotMatrixWidgetsUI* self);
DotMatrixPath* dot_matrix_path_new (void);
DotMatrixPath* dot_matrix_path_construct (GType object_type);
gpointer dot_matrix_path_ref (gpointer instance);
void dot_matrix_path_unref (gpointer instance);
GParamSpec* dot_matrix_param_spec_path (const gchar* name,
                                        const gchar* nick,
                                        const gchar* blurb,
                                        GType object_type,
                                        GParamFlags flags);
void dot_matrix_value_set_path (GValue* value,
                                gpointer v_object);
void dot_matrix_value_take_path (GValue* value,
                                 gpointer v_object);
gpointer dot_matrix_value_get_path (const GValue* value);
GType dot_matrix_path_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DotMatrixPath, dot_matrix_path_unref)
static void __dot_matrix_main_window___lambda11__gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self);
DotMatrixWidgetsUI* dot_matrix_widgets_ui_new (DotMatrixMainWindow* win,
                                               GtkDrawingArea* da);
DotMatrixWidgetsUI* dot_matrix_widgets_ui_construct (GType object_type,
                                                     DotMatrixMainWindow* win,
                                                     GtkDrawingArea* da);
static void _dot_matrix_main_window___lambda12_ (DotMatrixMainWindow* self,
                                          GtkColorButton* e);
gpointer dot_matrix_point_ref (gpointer instance);
void dot_matrix_point_unref (gpointer instance);
GParamSpec* dot_matrix_param_spec_point (const gchar* name,
                                         const gchar* nick,
                                         const gchar* blurb,
                                         GType object_type,
                                         GParamFlags flags);
void dot_matrix_value_set_point (GValue* value,
                                 gpointer v_object);
void dot_matrix_value_take_point (GValue* value,
                                  gpointer v_object);
gpointer dot_matrix_value_get_point (const GValue* value);
GType dot_matrix_point_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (DotMatrixPoint, dot_matrix_point_unref)
static void __dot_matrix_main_window___lambda12__gtk_color_button_color_set (GtkColorButton* _sender,
                                                                      gpointer self);
static void _dot_matrix_main_window___lambda13_ (DotMatrixMainWindow* self,
                                          GtkSpinButton* e);
static void __dot_matrix_main_window___lambda13__gtk_spin_button_value_changed (GtkSpinButton* _sender,
                                                                         gpointer self);
static void _dot_matrix_main_window___lambda14_ (DotMatrixMainWindow* self,
                                          GtkButton* e);
void dot_matrix_path_set_is_curve (DotMatrixPath* self,
                                   gboolean value);
void dot_matrix_path_set_is_reverse_curve (DotMatrixPath* self,
                                           gboolean value);
static void __dot_matrix_main_window___lambda14__gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self);
static void _dot_matrix_main_window___lambda15_ (DotMatrixMainWindow* self,
                                          GtkButton* e);
static void __dot_matrix_main_window___lambda15__gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self);
static void _dot_matrix_main_window___lambda16_ (DotMatrixMainWindow* self,
                                          GtkButton* e);
static void __dot_matrix_main_window___lambda16__gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self);
static void _dot_matrix_main_window___lambda17_ (DotMatrixMainWindow* self,
                                          GtkButton* e);
gboolean dot_matrix_path_get_is_closed (DotMatrixPath* self);
void dot_matrix_path_set_is_closed (DotMatrixPath* self,
                                    gboolean value);
static void __dot_matrix_main_window___lambda17__gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self);
static void dot_matrix_main_window_finalize (GObject * obj);
static GType dot_matrix_main_window_get_type_once (void);
static void _vala_dot_matrix_main_window_get_property (GObject * object,
                                                guint property_id,
                                                GValue * value,
                                                GParamSpec * pspec);
static void _vala_dot_matrix_main_window_set_property (GObject * object,
                                                guint property_id,
                                                const GValue * value,
                                                GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static const GActionEntry DOT_MATRIX_MAIN_WINDOW_ACTION_ENTRIES[2] = {{DOT_MATRIX_MAIN_WINDOW_ACTION_ABOUT, _dot_matrix_main_window_action_about_gsimple_action_activate_callback}, {DOT_MATRIX_MAIN_WINDOW_ACTION_KEYS, _dot_matrix_main_window_action_keys_gsimple_action_activate_callback}};

static inline gpointer
dot_matrix_main_window_get_instance_private (DotMatrixMainWindow* self)
{
	return G_STRUCT_MEMBER_P (self, DotMatrixMainWindow_private_offset);
}

static void
_dot_matrix_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                       GVariant* parameter,
                                                                       gpointer self)
{
#line 65 "../src/MainWindow.vala"
	dot_matrix_main_window_action_about ((DotMatrixMainWindow*) self);
#line 333 "MainWindow.c"
}

static void
_dot_matrix_main_window_action_keys_gsimple_action_activate_callback (GSimpleAction* action,
                                                                      GVariant* parameter,
                                                                      gpointer self)
{
#line 65 "../src/MainWindow.vala"
	dot_matrix_main_window_action_keys ((DotMatrixMainWindow*) self);
#line 343 "MainWindow.c"
}

DotMatrixMainWindow*
dot_matrix_main_window_construct (GType object_type,
                                  GtkApplication* application)
{
	DotMatrixMainWindow * self = NULL;
#line 71 "../src/MainWindow.vala"
	g_return_val_if_fail (application != NULL, NULL);
#line 72 "../src/MainWindow.vala"
	self = (DotMatrixMainWindow*) g_object_new (object_type, "application", application, "app", application, "icon-name", APP_ID, NULL);
#line 71 "../src/MainWindow.vala"
	return self;
#line 357 "MainWindow.c"
}

DotMatrixMainWindow*
dot_matrix_main_window_new (GtkApplication* application)
{
#line 71 "../src/MainWindow.vala"
	return dot_matrix_main_window_construct (DOT_MATRIX_TYPE_MAIN_WINDOW, application);
#line 365 "MainWindow.c"
}

static gboolean
dot_matrix_main_window_real_close_request (GtkWindow* base)
{
	DotMatrixMainWindow * self;
	DotMatrixWidgetsUI* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	gboolean result = FALSE;
#line 186 "../src/MainWindow.vala"
	self = (DotMatrixMainWindow*) base;
#line 187 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 187 "../src/MainWindow.vala"
	_tmp1_ = dot_matrix_widgets_ui_get_dirty (_tmp0_);
#line 187 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_;
#line 187 "../src/MainWindow.vala"
	if (_tmp2_) {
#line 386 "MainWindow.c"
		DotMatrixWidgetsUI* _tmp3_;
#line 188 "../src/MainWindow.vala"
		_tmp3_ = self->ui;
#line 188 "../src/MainWindow.vala"
		dot_matrix_widgets_ui_clear (_tmp3_);
#line 392 "MainWindow.c"
	}
#line 191 "../src/MainWindow.vala"
	g_object_run_dispose ((GObject*) self);
#line 192 "../src/MainWindow.vala"
	result = FALSE;
#line 192 "../src/MainWindow.vala"
	return result;
#line 400 "MainWindow.c"
}

void
dot_matrix_main_window_listen_to_changes (DotMatrixMainWindow* self)
{
	GSettings* _tmp0_;
	GSettings* _tmp1_;
#line 195 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 196 "../src/MainWindow.vala"
	_tmp0_ = dot_matrix_application_gsettings;
#line 196 "../src/MainWindow.vala"
	g_settings_bind (_tmp0_, "window-w", (GObject*) self, "default-width", G_SETTINGS_BIND_DEFAULT);
#line 197 "../src/MainWindow.vala"
	_tmp1_ = dot_matrix_application_gsettings;
#line 197 "../src/MainWindow.vala"
	g_settings_bind (_tmp1_, "window-h", (GObject*) self, "default-height", G_SETTINGS_BIND_DEFAULT);
#line 418 "MainWindow.c"
}

void
dot_matrix_main_window_action_about (DotMatrixMainWindow* self)
{
#line 201 "../src/MainWindow.vala"
	static const char COPYRIGHT[] = "Copyright \xc2\xa9 2019-2021 Paulo \"Lains\" Galardi\n";
#line 203 "../src/MainWindow.vala"
	static const gchar* AUTHORS[2] = {"Paulo \"Lains\" Galardi", NULL};
#line 428 "MainWindow.c"
	gchar* program_name = NULL;
	gchar* _tmp0_;
#line 200 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 208 "../src/MainWindow.vala"
	_tmp0_ = g_strconcat (NAME_PREFIX, _ ("Dot Matrix"), NULL);
#line 208 "../src/MainWindow.vala"
	program_name = _tmp0_;
#line 209 "../src/MainWindow.vala"
	gtk_show_about_dialog ((GtkWindow*) self, "program-name", program_name, "logo-icon-name", APP_ID, "version", VERSION, "comments", _ ("The glyph playground of creativity from simple lines."), "copyright", COPYRIGHT, "authors", AUTHORS, "artists", NULL, "license-type", GTK_LICENSE_GPL_3_0, "wrap-license", FALSE, "translator-credits", _ ("translator-credits"), NULL, NULL);
#line 200 "../src/MainWindow.vala"
	_g_free0 (program_name);
#line 441 "MainWindow.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 227 "../src/MainWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 449 "MainWindow.c"
}

void
dot_matrix_main_window_action_keys (DotMatrixMainWindow* self)
{
	GError* _inner_error0_ = NULL;
#line 223 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 458 "MainWindow.c"
	{
		GtkBuilder* build = NULL;
		GtkBuilder* _tmp0_;
		GtkShortcutsWindow* window = NULL;
		GObject* _tmp1_;
		GtkShortcutsWindow* _tmp2_;
		GtkShortcutsWindow* _tmp3_;
		GtkShortcutsWindow* _tmp4_;
#line 225 "../src/MainWindow.vala"
		_tmp0_ = gtk_builder_new ();
#line 225 "../src/MainWindow.vala"
		build = _tmp0_;
#line 226 "../src/MainWindow.vala"
		gtk_builder_add_from_resource (build, "/io/github/lainsce/DotMatrix/shortcuts.ui", &_inner_error0_);
#line 226 "../src/MainWindow.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 226 "../src/MainWindow.vala"
			_g_object_unref0 (build);
#line 477 "MainWindow.c"
			goto __catch0_g_error;
		}
#line 227 "../src/MainWindow.vala"
		_tmp1_ = gtk_builder_get_object (build, "shortcuts-dotmatrix");
#line 227 "../src/MainWindow.vala"
		_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_shortcuts_window_get_type (), GtkShortcutsWindow));
#line 227 "../src/MainWindow.vala"
		window = _tmp2_;
#line 228 "../src/MainWindow.vala"
		_tmp3_ = window;
#line 228 "../src/MainWindow.vala"
		gtk_window_set_transient_for ((GtkWindow*) _tmp3_, (GtkWindow*) self);
#line 229 "../src/MainWindow.vala"
		_tmp4_ = window;
#line 229 "../src/MainWindow.vala"
		gtk_widget_show ((GtkWidget*) _tmp4_);
#line 224 "../src/MainWindow.vala"
		_g_object_unref0 (window);
#line 224 "../src/MainWindow.vala"
		_g_object_unref0 (build);
#line 498 "MainWindow.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp5_;
		const gchar* _tmp6_;
#line 224 "../src/MainWindow.vala"
		e = _inner_error0_;
#line 224 "../src/MainWindow.vala"
		_inner_error0_ = NULL;
#line 231 "../src/MainWindow.vala"
		_tmp5_ = e;
#line 231 "../src/MainWindow.vala"
		_tmp6_ = _tmp5_->message;
#line 231 "../src/MainWindow.vala"
		g_warning ("MainWindow.vala:231: Failed to open shortcuts window: %s\n", _tmp6_);
#line 224 "../src/MainWindow.vala"
		_g_error_free0 (e);
#line 518 "MainWindow.c"
	}
	__finally0:
#line 224 "../src/MainWindow.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 224 "../src/MainWindow.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 224 "../src/MainWindow.vala"
		g_clear_error (&_inner_error0_);
#line 224 "../src/MainWindow.vala"
		return;
#line 529 "MainWindow.c"
	}
}

GSimpleActionGroup*
dot_matrix_main_window_get_actions (DotMatrixMainWindow* self)
{
	GSimpleActionGroup* result;
	GSimpleActionGroup* _tmp0_;
#line 59 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 59 "../src/MainWindow.vala"
	_tmp0_ = self->priv->_actions;
#line 59 "../src/MainWindow.vala"
	result = _tmp0_;
#line 59 "../src/MainWindow.vala"
	return result;
#line 546 "MainWindow.c"
}

static void
dot_matrix_main_window_set_actions (DotMatrixMainWindow* self,
                                    GSimpleActionGroup* value)
{
	GSimpleActionGroup* old_value;
#line 59 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 59 "../src/MainWindow.vala"
	old_value = dot_matrix_main_window_get_actions (self);
#line 59 "../src/MainWindow.vala"
	if (old_value != value) {
#line 560 "MainWindow.c"
		GSimpleActionGroup* _tmp0_;
#line 59 "../src/MainWindow.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 59 "../src/MainWindow.vala"
		_g_object_unref0 (self->priv->_actions);
#line 59 "../src/MainWindow.vala"
		self->priv->_actions = _tmp0_;
#line 59 "../src/MainWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, dot_matrix_main_window_properties[DOT_MATRIX_MAIN_WINDOW_ACTIONS_PROPERTY]);
#line 570 "MainWindow.c"
	}
}

GtkApplication*
dot_matrix_main_window_get_app (DotMatrixMainWindow* self)
{
	GtkApplication* result;
	GtkApplication* _tmp0_;
#line 70 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 70 "../src/MainWindow.vala"
	_tmp0_ = self->priv->_app;
#line 70 "../src/MainWindow.vala"
	result = _tmp0_;
#line 70 "../src/MainWindow.vala"
	return result;
#line 587 "MainWindow.c"
}

static void
dot_matrix_main_window_set_app (DotMatrixMainWindow* self,
                                GtkApplication* value)
{
	GtkApplication* old_value;
#line 70 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 70 "../src/MainWindow.vala"
	old_value = dot_matrix_main_window_get_app (self);
#line 70 "../src/MainWindow.vala"
	if (old_value != value) {
#line 601 "MainWindow.c"
		GtkApplication* _tmp0_;
#line 70 "../src/MainWindow.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 70 "../src/MainWindow.vala"
		_g_object_unref0 (self->priv->_app);
#line 70 "../src/MainWindow.vala"
		self->priv->_app = _tmp0_;
#line 70 "../src/MainWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, dot_matrix_main_window_properties[DOT_MATRIX_MAIN_WINDOW_APP_PROPERTY]);
#line 611 "MainWindow.c"
	}
}

static void
_vala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
#line 104 "../src/MainWindow.vala"
	if ((*length) == (*size)) {
#line 104 "../src/MainWindow.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 104 "../src/MainWindow.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 627 "MainWindow.c"
	}
#line 104 "../src/MainWindow.vala"
	(*array)[(*length)++] = value;
#line 104 "../src/MainWindow.vala"
	(*array)[*length] = NULL;
#line 633 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda9_ (DotMatrixMainWindow* self,
                                    GtkButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
#line 110 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 111 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 111 "../src/MainWindow.vala"
	dot_matrix_widgets_ui_clear (_tmp0_);
#line 647 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda9__gtk_button_clicked (GtkButton* _sender,
                                                        gpointer self)
{
#line 110 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda9_ ((DotMatrixMainWindow*) self, _sender);
#line 656 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda10_ (DotMatrixMainWindow* self,
                                     GtkButton* e)
{
	GError* _inner_error0_ = NULL;
#line 114 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 666 "MainWindow.c"
	{
		DotMatrixWidgetsUI* _tmp0_;
#line 116 "../src/MainWindow.vala"
		_tmp0_ = self->ui;
#line 116 "../src/MainWindow.vala"
		dot_matrix_widgets_ui_save (_tmp0_, NULL, NULL);
#line 673 "MainWindow.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp1_;
		const gchar* _tmp2_;
		gchar* _tmp3_;
		gchar* _tmp4_;
#line 115 "../src/MainWindow.vala"
		e = _inner_error0_;
#line 115 "../src/MainWindow.vala"
		_inner_error0_ = NULL;
#line 118 "../src/MainWindow.vala"
		_tmp1_ = e;
#line 118 "../src/MainWindow.vala"
		_tmp2_ = _tmp1_->message;
#line 118 "../src/MainWindow.vala"
		_tmp3_ = g_strconcat ("Unexpected error during save: ", _tmp2_, NULL);
#line 118 "../src/MainWindow.vala"
		_tmp4_ = _tmp3_;
#line 118 "../src/MainWindow.vala"
		g_warning ("MainWindow.vala:118: %s", _tmp4_);
#line 118 "../src/MainWindow.vala"
		_g_free0 (_tmp4_);
#line 115 "../src/MainWindow.vala"
		_g_error_free0 (e);
#line 701 "MainWindow.c"
	}
	__finally0:
#line 115 "../src/MainWindow.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 115 "../src/MainWindow.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 115 "../src/MainWindow.vala"
		g_clear_error (&_inner_error0_);
#line 115 "../src/MainWindow.vala"
		return;
#line 712 "MainWindow.c"
	}
}

static void
__dot_matrix_main_window___lambda10__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self)
{
#line 114 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda10_ ((DotMatrixMainWindow*) self, _sender);
#line 722 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda11_ (DotMatrixMainWindow* self,
                                     GtkButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
	DotMatrixWidgetsUI* _tmp1_;
	DotMatrixPath* _tmp2_;
	DotMatrixWidgetsUI* _tmp3_;
	GtkDrawingArea* _tmp4_;
#line 122 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 123 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 123 "../src/MainWindow.vala"
	dot_matrix_widgets_ui_undo (_tmp0_);
#line 124 "../src/MainWindow.vala"
	_tmp1_ = self->ui;
#line 124 "../src/MainWindow.vala"
	_tmp2_ = dot_matrix_path_new ();
#line 124 "../src/MainWindow.vala"
	_dot_matrix_path_unref0 (_tmp1_->current_path);
#line 124 "../src/MainWindow.vala"
	_tmp1_->current_path = _tmp2_;
#line 125 "../src/MainWindow.vala"
	_tmp3_ = self->ui;
#line 125 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_->da;
#line 125 "../src/MainWindow.vala"
	gtk_widget_queue_draw ((GtkWidget*) _tmp4_);
#line 754 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda11__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self)
{
#line 122 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda11_ ((DotMatrixMainWindow*) self, _sender);
#line 763 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda12_ (DotMatrixMainWindow* self,
                                     GtkColorButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
	DotMatrixPath* _tmp1_;
	GtkColorButton* _tmp2_;
	GdkRGBA _tmp3_ = {0};
	GdkRGBA _tmp4_;
	DotMatrixWidgetsUI* _tmp5_;
	GtkDrawingArea* _tmp6_;
#line 137 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 138 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 138 "../src/MainWindow.vala"
	_tmp1_ = _tmp0_->current_path;
#line 138 "../src/MainWindow.vala"
	_tmp2_ = self->line_color_button;
#line 138 "../src/MainWindow.vala"
	gtk_color_chooser_get_rgba ((GtkColorChooser*) _tmp2_, &_tmp3_);
#line 138 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 138 "../src/MainWindow.vala"
	_tmp1_->color = _tmp4_;
#line 139 "../src/MainWindow.vala"
	_tmp5_ = self->ui;
#line 139 "../src/MainWindow.vala"
	_tmp6_ = _tmp5_->da;
#line 139 "../src/MainWindow.vala"
	gtk_widget_queue_draw ((GtkWidget*) _tmp6_);
#line 797 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda12__gtk_color_button_color_set (GtkColorButton* _sender,
                                                                 gpointer self)
{
#line 137 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda12_ ((DotMatrixMainWindow*) self, _sender);
#line 806 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda13_ (DotMatrixMainWindow* self,
                                     GtkSpinButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
	GtkSpinButton* _tmp1_;
#line 142 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 143 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 143 "../src/MainWindow.vala"
	_tmp1_ = self->line_thickness_button;
#line 143 "../src/MainWindow.vala"
	_tmp0_->line_thickness = gtk_spin_button_get_value (_tmp1_);
#line 823 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda13__gtk_spin_button_value_changed (GtkSpinButton* _sender,
                                                                    gpointer self)
{
#line 142 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda13_ ((DotMatrixMainWindow*) self, _sender);
#line 832 "MainWindow.c"
}

static gpointer
_dot_matrix_path_ref0 (gpointer self)
{
#line 147 "../src/MainWindow.vala"
	return self ? dot_matrix_path_ref (self) : NULL;
#line 840 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda14_ (DotMatrixMainWindow* self,
                                     GtkButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
	DotMatrixWidgetsUI* _tmp1_;
	DotMatrixPath* _tmp2_;
	DotMatrixPath* _tmp3_;
	DotMatrixWidgetsUI* _tmp4_;
	DotMatrixPath* _tmp5_;
	DotMatrixWidgetsUI* _tmp6_;
	DotMatrixPath* _tmp7_;
	DotMatrixWidgetsUI* _tmp8_;
	DotMatrixPath* _tmp9_;
	DotMatrixWidgetsUI* _tmp10_;
	GtkDrawingArea* _tmp11_;
#line 146 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 147 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 147 "../src/MainWindow.vala"
	_tmp1_ = self->ui;
#line 147 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_->current_path;
#line 147 "../src/MainWindow.vala"
	_tmp3_ = _dot_matrix_path_ref0 (_tmp2_);
#line 147 "../src/MainWindow.vala"
	_tmp0_->paths = g_list_append (_tmp0_->paths, _tmp3_);
#line 148 "../src/MainWindow.vala"
	_tmp4_ = self->ui;
#line 148 "../src/MainWindow.vala"
	_tmp5_ = _tmp4_->current_path;
#line 148 "../src/MainWindow.vala"
	dot_matrix_path_set_is_curve (_tmp5_, TRUE);
#line 149 "../src/MainWindow.vala"
	_tmp6_ = self->ui;
#line 149 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_->current_path;
#line 149 "../src/MainWindow.vala"
	dot_matrix_path_set_is_reverse_curve (_tmp7_, FALSE);
#line 150 "../src/MainWindow.vala"
	_tmp8_ = self->ui;
#line 150 "../src/MainWindow.vala"
	_tmp9_ = dot_matrix_path_new ();
#line 150 "../src/MainWindow.vala"
	_dot_matrix_path_unref0 (_tmp8_->current_path);
#line 150 "../src/MainWindow.vala"
	_tmp8_->current_path = _tmp9_;
#line 151 "../src/MainWindow.vala"
	_tmp10_ = self->ui;
#line 151 "../src/MainWindow.vala"
	_tmp11_ = _tmp10_->da;
#line 151 "../src/MainWindow.vala"
	gtk_widget_queue_draw ((GtkWidget*) _tmp11_);
#line 897 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda14__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self)
{
#line 146 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda14_ ((DotMatrixMainWindow*) self, _sender);
#line 906 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda15_ (DotMatrixMainWindow* self,
                                     GtkButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
	DotMatrixWidgetsUI* _tmp1_;
	DotMatrixPath* _tmp2_;
	DotMatrixPath* _tmp3_;
	DotMatrixWidgetsUI* _tmp4_;
	DotMatrixPath* _tmp5_;
	DotMatrixWidgetsUI* _tmp6_;
	DotMatrixPath* _tmp7_;
	DotMatrixWidgetsUI* _tmp8_;
	DotMatrixPath* _tmp9_;
	DotMatrixWidgetsUI* _tmp10_;
	GtkDrawingArea* _tmp11_;
#line 154 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 155 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 155 "../src/MainWindow.vala"
	_tmp1_ = self->ui;
#line 155 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_->current_path;
#line 155 "../src/MainWindow.vala"
	_tmp3_ = _dot_matrix_path_ref0 (_tmp2_);
#line 155 "../src/MainWindow.vala"
	_tmp0_->paths = g_list_append (_tmp0_->paths, _tmp3_);
#line 156 "../src/MainWindow.vala"
	_tmp4_ = self->ui;
#line 156 "../src/MainWindow.vala"
	_tmp5_ = _tmp4_->current_path;
#line 156 "../src/MainWindow.vala"
	dot_matrix_path_set_is_curve (_tmp5_, TRUE);
#line 157 "../src/MainWindow.vala"
	_tmp6_ = self->ui;
#line 157 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_->current_path;
#line 157 "../src/MainWindow.vala"
	dot_matrix_path_set_is_reverse_curve (_tmp7_, TRUE);
#line 158 "../src/MainWindow.vala"
	_tmp8_ = self->ui;
#line 158 "../src/MainWindow.vala"
	_tmp9_ = dot_matrix_path_new ();
#line 158 "../src/MainWindow.vala"
	_dot_matrix_path_unref0 (_tmp8_->current_path);
#line 158 "../src/MainWindow.vala"
	_tmp8_->current_path = _tmp9_;
#line 159 "../src/MainWindow.vala"
	_tmp10_ = self->ui;
#line 159 "../src/MainWindow.vala"
	_tmp11_ = _tmp10_->da;
#line 159 "../src/MainWindow.vala"
	gtk_widget_queue_draw ((GtkWidget*) _tmp11_);
#line 963 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda15__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self)
{
#line 154 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda15_ ((DotMatrixMainWindow*) self, _sender);
#line 972 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda16_ (DotMatrixMainWindow* self,
                                     GtkButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
	DotMatrixWidgetsUI* _tmp1_;
	DotMatrixPath* _tmp2_;
	DotMatrixPath* _tmp3_;
	DotMatrixWidgetsUI* _tmp4_;
	DotMatrixPath* _tmp5_;
	DotMatrixWidgetsUI* _tmp6_;
	DotMatrixPath* _tmp7_;
	DotMatrixWidgetsUI* _tmp8_;
	GtkDrawingArea* _tmp9_;
#line 162 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 163 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 163 "../src/MainWindow.vala"
	_tmp1_ = self->ui;
#line 163 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_->current_path;
#line 163 "../src/MainWindow.vala"
	_tmp3_ = _dot_matrix_path_ref0 (_tmp2_);
#line 163 "../src/MainWindow.vala"
	_tmp0_->paths = g_list_append (_tmp0_->paths, _tmp3_);
#line 164 "../src/MainWindow.vala"
	_tmp4_ = self->ui;
#line 164 "../src/MainWindow.vala"
	_tmp5_ = _tmp4_->current_path;
#line 164 "../src/MainWindow.vala"
	dot_matrix_path_set_is_curve (_tmp5_, FALSE);
#line 165 "../src/MainWindow.vala"
	_tmp6_ = self->ui;
#line 165 "../src/MainWindow.vala"
	_tmp7_ = dot_matrix_path_new ();
#line 165 "../src/MainWindow.vala"
	_dot_matrix_path_unref0 (_tmp6_->current_path);
#line 165 "../src/MainWindow.vala"
	_tmp6_->current_path = _tmp7_;
#line 166 "../src/MainWindow.vala"
	_tmp8_ = self->ui;
#line 166 "../src/MainWindow.vala"
	_tmp9_ = _tmp8_->da;
#line 166 "../src/MainWindow.vala"
	gtk_widget_queue_draw ((GtkWidget*) _tmp9_);
#line 1021 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda16__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self)
{
#line 162 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda16_ ((DotMatrixMainWindow*) self, _sender);
#line 1030 "MainWindow.c"
}

static void
_dot_matrix_main_window___lambda17_ (DotMatrixMainWindow* self,
                                     GtkButton* e)
{
	DotMatrixWidgetsUI* _tmp0_;
	DotMatrixWidgetsUI* _tmp1_;
	DotMatrixPath* _tmp2_;
	DotMatrixPath* _tmp3_;
	DotMatrixWidgetsUI* _tmp4_;
	DotMatrixPath* _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	DotMatrixWidgetsUI* _tmp16_;
	DotMatrixPath* _tmp17_;
	DotMatrixWidgetsUI* _tmp18_;
	GtkDrawingArea* _tmp19_;
#line 169 "../src/MainWindow.vala"
	g_return_if_fail (e != NULL);
#line 170 "../src/MainWindow.vala"
	_tmp0_ = self->ui;
#line 170 "../src/MainWindow.vala"
	_tmp1_ = self->ui;
#line 170 "../src/MainWindow.vala"
	_tmp2_ = _tmp1_->current_path;
#line 170 "../src/MainWindow.vala"
	_tmp3_ = _dot_matrix_path_ref0 (_tmp2_);
#line 170 "../src/MainWindow.vala"
	_tmp0_->paths = g_list_append (_tmp0_->paths, _tmp3_);
#line 171 "../src/MainWindow.vala"
	_tmp4_ = self->ui;
#line 171 "../src/MainWindow.vala"
	_tmp5_ = _tmp4_->current_path;
#line 171 "../src/MainWindow.vala"
	_tmp6_ = dot_matrix_path_get_is_closed (_tmp5_);
#line 171 "../src/MainWindow.vala"
	_tmp7_ = _tmp6_;
#line 171 "../src/MainWindow.vala"
	if (_tmp7_ == TRUE) {
#line 1071 "MainWindow.c"
		DotMatrixWidgetsUI* _tmp8_;
		DotMatrixPath* _tmp9_;
#line 172 "../src/MainWindow.vala"
		_tmp8_ = self->ui;
#line 172 "../src/MainWindow.vala"
		_tmp9_ = _tmp8_->current_path;
#line 172 "../src/MainWindow.vala"
		dot_matrix_path_set_is_closed (_tmp9_, FALSE);
#line 1080 "MainWindow.c"
	} else {
		DotMatrixWidgetsUI* _tmp10_;
		DotMatrixPath* _tmp11_;
		gboolean _tmp12_;
		gboolean _tmp13_;
#line 173 "../src/MainWindow.vala"
		_tmp10_ = self->ui;
#line 173 "../src/MainWindow.vala"
		_tmp11_ = _tmp10_->current_path;
#line 173 "../src/MainWindow.vala"
		_tmp12_ = dot_matrix_path_get_is_closed (_tmp11_);
#line 173 "../src/MainWindow.vala"
		_tmp13_ = _tmp12_;
#line 173 "../src/MainWindow.vala"
		if (_tmp13_ == FALSE) {
#line 1096 "MainWindow.c"
			DotMatrixWidgetsUI* _tmp14_;
			DotMatrixPath* _tmp15_;
#line 174 "../src/MainWindow.vala"
			_tmp14_ = self->ui;
#line 174 "../src/MainWindow.vala"
			_tmp15_ = _tmp14_->current_path;
#line 174 "../src/MainWindow.vala"
			dot_matrix_path_set_is_closed (_tmp15_, TRUE);
#line 1105 "MainWindow.c"
		}
	}
#line 176 "../src/MainWindow.vala"
	_tmp16_ = self->ui;
#line 176 "../src/MainWindow.vala"
	_tmp17_ = dot_matrix_path_new ();
#line 176 "../src/MainWindow.vala"
	_dot_matrix_path_unref0 (_tmp16_->current_path);
#line 176 "../src/MainWindow.vala"
	_tmp16_->current_path = _tmp17_;
#line 177 "../src/MainWindow.vala"
	_tmp18_ = self->ui;
#line 177 "../src/MainWindow.vala"
	_tmp19_ = _tmp18_->da;
#line 177 "../src/MainWindow.vala"
	gtk_widget_queue_draw ((GtkWidget*) _tmp19_);
#line 1122 "MainWindow.c"
}

static void
__dot_matrix_main_window___lambda17__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self)
{
#line 169 "../src/MainWindow.vala"
	_dot_matrix_main_window___lambda17_ ((DotMatrixMainWindow*) self, _sender);
#line 1131 "MainWindow.c"
}

static GObject *
dot_matrix_main_window_constructor (GType type,
                                    guint n_construct_properties,
                                    GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	DotMatrixMainWindow * self;
	GtkCssProvider* provider = NULL;
	GtkCssProvider* _tmp0_;
	GtkCssProvider* _tmp1_;
	GdkDisplay* _tmp2_;
	GtkCssProvider* _tmp3_;
	GtkIconTheme* theme = NULL;
	GdkDisplay* _tmp4_;
	GtkIconTheme* _tmp5_;
	GtkIconTheme* _tmp6_;
	GtkIconTheme* _tmp7_;
	GtkStyleContext* style = NULL;
	GtkStyleContext* _tmp8_;
	GtkStyleContext* _tmp9_;
	GSimpleActionGroup* _tmp11_;
	GSimpleActionGroup* _tmp12_;
	GSimpleActionGroup* _tmp13_;
	GSimpleActionGroup* _tmp14_;
	GtkButton* _tmp35_;
	GtkButton* _tmp36_;
	GtkButton* _tmp37_;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp38_;
	GtkMenuButton* _tmp39_;
	GtkBuilder* _tmp40_;
	GObject* _tmp41_;
	GtkDrawingArea* _tmp42_;
	DotMatrixWidgetsUI* _tmp43_;
	DotMatrixWidgetsUI* _tmp44_;
	const gchar* _tmp45_;
	DotMatrixWidgetsUI* _tmp46_;
	const gchar* _tmp47_;
	DotMatrixWidgetsUI* _tmp48_;
	const gchar* _tmp49_;
	GtkColorButton* _tmp50_;
	DotMatrixWidgetsUI* _tmp51_;
	GdkRGBA _tmp52_;
	GtkColorButton* _tmp53_;
	GtkSpinButton* _tmp54_;
	GtkButton* _tmp55_;
	GtkButton* _tmp56_;
	GtkButton* _tmp57_;
	GtkButton* _tmp58_;
#line 79 "../src/MainWindow.vala"
	parent_class = G_OBJECT_CLASS (dot_matrix_main_window_parent_class);
#line 79 "../src/MainWindow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 79 "../src/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindow);
#line 81 "../src/MainWindow.vala"
	adw_init ();
#line 83 "../src/MainWindow.vala"
	_tmp0_ = gtk_css_provider_new ();
#line 83 "../src/MainWindow.vala"
	provider = _tmp0_;
#line 84 "../src/MainWindow.vala"
	_tmp1_ = provider;
#line 84 "../src/MainWindow.vala"
	gtk_css_provider_load_from_resource (_tmp1_, "/io/github/lainsce/DotMatrix/app.css");
#line 85 "../src/MainWindow.vala"
	_tmp2_ = gdk_display_get_default ();
#line 85 "../src/MainWindow.vala"
	_tmp3_ = provider;
#line 85 "../src/MainWindow.vala"
	gtk_style_context_add_provider_for_display (_tmp2_, (GtkStyleProvider*) _tmp3_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 89 "../src/MainWindow.vala"
	_tmp4_ = gdk_display_get_default ();
#line 89 "../src/MainWindow.vala"
	_tmp5_ = gtk_icon_theme_get_for_display (_tmp4_);
#line 89 "../src/MainWindow.vala"
	_tmp6_ = _g_object_ref0 (_tmp5_);
#line 89 "../src/MainWindow.vala"
	theme = _tmp6_;
#line 90 "../src/MainWindow.vala"
	_tmp7_ = theme;
#line 90 "../src/MainWindow.vala"
	gtk_icon_theme_add_resource_path (_tmp7_, "/io/github/lainsce/DotMatrix");
#line 92 "../src/MainWindow.vala"
	_tmp8_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 92 "../src/MainWindow.vala"
	_tmp9_ = _g_object_ref0 (_tmp8_);
#line 92 "../src/MainWindow.vala"
	style = _tmp9_;
#line 93 "../src/MainWindow.vala"
	if (g_strcmp0 (PROFILE, "Devel") == 0) {
#line 1226 "MainWindow.c"
		GtkStyleContext* _tmp10_;
#line 94 "../src/MainWindow.vala"
		_tmp10_ = style;
#line 94 "../src/MainWindow.vala"
		gtk_style_context_add_class (_tmp10_, "devel");
#line 1232 "MainWindow.c"
	}
#line 98 "../src/MainWindow.vala"
	_tmp11_ = g_simple_action_group_new ();
#line 98 "../src/MainWindow.vala"
	_tmp12_ = _tmp11_;
#line 98 "../src/MainWindow.vala"
	dot_matrix_main_window_set_actions (self, _tmp12_);
#line 98 "../src/MainWindow.vala"
	_g_object_unref0 (_tmp12_);
#line 99 "../src/MainWindow.vala"
	_tmp13_ = self->priv->_actions;
#line 99 "../src/MainWindow.vala"
	g_action_map_add_action_entries ((GActionMap*) _tmp13_, DOT_MATRIX_MAIN_WINDOW_ACTION_ENTRIES, (gint) G_N_ELEMENTS (DOT_MATRIX_MAIN_WINDOW_ACTION_ENTRIES), self);
#line 100 "../src/MainWindow.vala"
	_tmp14_ = self->priv->_actions;
#line 100 "../src/MainWindow.vala"
	gtk_widget_insert_action_group ((GtkWidget*) self, "win", (GActionGroup*) _tmp14_);
#line 1250 "MainWindow.c"
	{
		GeeIterator* _action_it = NULL;
		GeeMultiMap* _tmp15_;
		GeeSet* _tmp16_;
		GeeSet* _tmp17_;
		GeeIterator* _tmp18_;
		GeeIterator* _tmp19_;
#line 102 "../src/MainWindow.vala"
		_tmp15_ = dot_matrix_main_window_action_accelerators;
#line 102 "../src/MainWindow.vala"
		_tmp16_ = gee_multi_map_get_keys (_tmp15_);
#line 102 "../src/MainWindow.vala"
		_tmp17_ = _tmp16_;
#line 102 "../src/MainWindow.vala"
		_tmp18_ = gee_iterable_iterator ((GeeIterable*) _tmp17_);
#line 102 "../src/MainWindow.vala"
		_tmp19_ = _tmp18_;
#line 102 "../src/MainWindow.vala"
		_g_object_unref0 (_tmp17_);
#line 102 "../src/MainWindow.vala"
		_action_it = _tmp19_;
#line 102 "../src/MainWindow.vala"
		while (TRUE) {
#line 1274 "MainWindow.c"
			GeeIterator* _tmp20_;
			gchar* action = NULL;
			GeeIterator* _tmp21_;
			gpointer _tmp22_;
			gchar** accels_array = NULL;
			GeeMultiMap* _tmp23_;
			const gchar* _tmp24_;
			GeeCollection* _tmp25_;
			GeeCollection* _tmp26_;
			gint _tmp27_ = 0;
			gpointer* _tmp28_;
			gchar** _tmp29_;
			gint _tmp29__length1;
			gint accels_array_length1;
			gint _accels_array_size_;
			GtkApplication* _tmp30_;
			const gchar* _tmp31_;
			gchar* _tmp32_;
			gchar* _tmp33_;
			gchar** _tmp34_;
			gint _tmp34__length1;
#line 102 "../src/MainWindow.vala"
			_tmp20_ = _action_it;
#line 102 "../src/MainWindow.vala"
			if (!gee_iterator_next (_tmp20_)) {
#line 102 "../src/MainWindow.vala"
				break;
#line 1302 "MainWindow.c"
			}
#line 102 "../src/MainWindow.vala"
			_tmp21_ = _action_it;
#line 102 "../src/MainWindow.vala"
			_tmp22_ = gee_iterator_get (_tmp21_);
#line 102 "../src/MainWindow.vala"
			action = (gchar*) _tmp22_;
#line 103 "../src/MainWindow.vala"
			_tmp23_ = dot_matrix_main_window_action_accelerators;
#line 103 "../src/MainWindow.vala"
			_tmp24_ = action;
#line 103 "../src/MainWindow.vala"
			_tmp25_ = gee_multi_map_get (_tmp23_, _tmp24_);
#line 103 "../src/MainWindow.vala"
			_tmp26_ = _tmp25_;
#line 103 "../src/MainWindow.vala"
			_tmp28_ = gee_collection_to_array (_tmp26_, &_tmp27_);
#line 103 "../src/MainWindow.vala"
			_tmp29_ = _tmp28_;
#line 103 "../src/MainWindow.vala"
			_tmp29__length1 = _tmp27_;
#line 103 "../src/MainWindow.vala"
			_g_object_unref0 (_tmp26_);
#line 103 "../src/MainWindow.vala"
			accels_array = _tmp29_;
#line 103 "../src/MainWindow.vala"
			accels_array_length1 = _tmp29__length1;
#line 103 "../src/MainWindow.vala"
			_accels_array_size_ = accels_array_length1;
#line 104 "../src/MainWindow.vala"
			_vala_array_add1 (&accels_array, &accels_array_length1, &_accels_array_size_, NULL);
#line 106 "../src/MainWindow.vala"
			_tmp30_ = self->priv->_app;
#line 106 "../src/MainWindow.vala"
			_tmp31_ = action;
#line 106 "../src/MainWindow.vala"
			_tmp32_ = g_strconcat (DOT_MATRIX_MAIN_WINDOW_ACTION_PREFIX, _tmp31_, NULL);
#line 106 "../src/MainWindow.vala"
			_tmp33_ = _tmp32_;
#line 106 "../src/MainWindow.vala"
			_tmp34_ = accels_array;
#line 106 "../src/MainWindow.vala"
			_tmp34__length1 = accels_array_length1;
#line 106 "../src/MainWindow.vala"
			gtk_application_set_accels_for_action (_tmp30_, _tmp33_, _tmp34_);
#line 106 "../src/MainWindow.vala"
			_g_free0 (_tmp33_);
#line 102 "../src/MainWindow.vala"
			accels_array = (_vala_array_free (accels_array, accels_array_length1, (GDestroyNotify) g_free), NULL);
#line 102 "../src/MainWindow.vala"
			_g_free0 (action);
#line 1354 "MainWindow.c"
		}
#line 102 "../src/MainWindow.vala"
		_g_object_unref0 (_action_it);
#line 1358 "MainWindow.c"
	}
#line 110 "../src/MainWindow.vala"
	_tmp35_ = self->new_button;
#line 110 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp35_, "clicked", (GCallback) __dot_matrix_main_window___lambda9__gtk_button_clicked, self, 0);
#line 114 "../src/MainWindow.vala"
	_tmp36_ = self->save_button;
#line 114 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp36_, "clicked", (GCallback) __dot_matrix_main_window___lambda10__gtk_button_clicked, self, 0);
#line 122 "../src/MainWindow.vala"
	_tmp37_ = self->undo_button;
#line 122 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp37_, "clicked", (GCallback) __dot_matrix_main_window___lambda11__gtk_button_clicked, self, 0);
#line 128 "../src/MainWindow.vala"
	_tmp38_ = gtk_builder_new_from_resource ("/io/github/lainsce/DotMatrix/menu.ui");
#line 128 "../src/MainWindow.vala"
	builder = _tmp38_;
#line 129 "../src/MainWindow.vala"
	_tmp39_ = self->menu_button;
#line 129 "../src/MainWindow.vala"
	_tmp40_ = builder;
#line 129 "../src/MainWindow.vala"
	_tmp41_ = gtk_builder_get_object (_tmp40_, "menu");
#line 129 "../src/MainWindow.vala"
	gtk_menu_button_set_menu_model (_tmp39_, G_TYPE_CHECK_INSTANCE_CAST (_tmp41_, g_menu_model_get_type (), GMenuModel));
#line 131 "../src/MainWindow.vala"
	_tmp42_ = self->da;
#line 131 "../src/MainWindow.vala"
	_tmp43_ = dot_matrix_widgets_ui_new (self, _tmp42_);
#line 131 "../src/MainWindow.vala"
	_dot_matrix_widgets_ui_unref0 (self->ui);
#line 131 "../src/MainWindow.vala"
	self->ui = _tmp43_;
#line 132 "../src/MainWindow.vala"
	_tmp44_ = self->ui;
#line 132 "../src/MainWindow.vala"
	_tmp45_ = self->b_med;
#line 132 "../src/MainWindow.vala"
	gdk_rgba_parse (&_tmp44_->grid_main_dot_color, _tmp45_);
#line 133 "../src/MainWindow.vala"
	_tmp46_ = self->ui;
#line 133 "../src/MainWindow.vala"
	_tmp47_ = self->b_low;
#line 133 "../src/MainWindow.vala"
	gdk_rgba_parse (&_tmp46_->grid_dot_color, _tmp47_);
#line 134 "../src/MainWindow.vala"
	_tmp48_ = self->ui;
#line 134 "../src/MainWindow.vala"
	_tmp49_ = self->background;
#line 134 "../src/MainWindow.vala"
	gdk_rgba_parse (&_tmp48_->background_color, _tmp49_);
#line 136 "../src/MainWindow.vala"
	_tmp50_ = self->line_color_button;
#line 136 "../src/MainWindow.vala"
	_tmp51_ = self->ui;
#line 136 "../src/MainWindow.vala"
	_tmp52_ = _tmp51_->line_color;
#line 136 "../src/MainWindow.vala"
	gtk_color_chooser_set_rgba ((GtkColorChooser*) _tmp50_, &_tmp52_);
#line 137 "../src/MainWindow.vala"
	_tmp53_ = self->line_color_button;
#line 137 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp53_, "color-set", (GCallback) __dot_matrix_main_window___lambda12__gtk_color_button_color_set, self, 0);
#line 142 "../src/MainWindow.vala"
	_tmp54_ = self->line_thickness_button;
#line 142 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp54_, "value-changed", (GCallback) __dot_matrix_main_window___lambda13__gtk_spin_button_value_changed, self, 0);
#line 146 "../src/MainWindow.vala"
	_tmp55_ = self->line_curve_button;
#line 146 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp55_, "clicked", (GCallback) __dot_matrix_main_window___lambda14__gtk_button_clicked, self, 0);
#line 154 "../src/MainWindow.vala"
	_tmp56_ = self->line_curve_reverse_button;
#line 154 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp56_, "clicked", (GCallback) __dot_matrix_main_window___lambda15__gtk_button_clicked, self, 0);
#line 162 "../src/MainWindow.vala"
	_tmp57_ = self->line_straight_button;
#line 162 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp57_, "clicked", (GCallback) __dot_matrix_main_window___lambda16__gtk_button_clicked, self, 0);
#line 169 "../src/MainWindow.vala"
	_tmp58_ = self->close_path_button;
#line 169 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp58_, "clicked", (GCallback) __dot_matrix_main_window___lambda17__gtk_button_clicked, self, 0);
#line 180 "../src/MainWindow.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, 360, 240);
#line 181 "../src/MainWindow.vala"
	dot_matrix_main_window_listen_to_changes (self);
#line 182 "../src/MainWindow.vala"
	gtk_widget_show ((GtkWidget*) self);
#line 183 "../src/MainWindow.vala"
	gtk_window_present ((GtkWindow*) self);
#line 79 "../src/MainWindow.vala"
	_g_object_unref0 (builder);
#line 79 "../src/MainWindow.vala"
	_g_object_unref0 (style);
#line 79 "../src/MainWindow.vala"
	_g_object_unref0 (theme);
#line 79 "../src/MainWindow.vala"
	_g_object_unref0 (provider);
#line 79 "../src/MainWindow.vala"
	return obj;
#line 1460 "MainWindow.c"
}

static void
dot_matrix_main_window_class_init (DotMatrixMainWindowClass * klass,
                                   gpointer klass_data)
{
	GeeHashMultiMap* _tmp0_;
#line 21 "../src/MainWindow.vala"
	dot_matrix_main_window_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/MainWindow.vala"
	g_type_class_adjust_private_offset (klass, &DotMatrixMainWindow_private_offset);
#line 21 "../src/MainWindow.vala"
	((GtkWindowClass *) klass)->close_request = (gboolean (*) (GtkWindow*)) dot_matrix_main_window_real_close_request;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_dot_matrix_main_window_get_property;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_dot_matrix_main_window_set_property;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->constructor = dot_matrix_main_window_constructor;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = dot_matrix_main_window_finalize;
#line 21 "../src/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), DOT_MATRIX_MAIN_WINDOW_ACTIONS_PROPERTY, dot_matrix_main_window_properties[DOT_MATRIX_MAIN_WINDOW_ACTIONS_PROPERTY] = g_param_spec_object ("actions", "actions", "actions", g_simple_action_group_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 21 "../src/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), DOT_MATRIX_MAIN_WINDOW_APP_PROPERTY, dot_matrix_main_window_properties[DOT_MATRIX_MAIN_WINDOW_APP_PROPERTY] = g_param_spec_object ("app", "app", "app", gtk_application_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/lainsce/DotMatrix/mainwindow.ui");
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "new_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, new_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "save_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, save_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "undo_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, undo_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, menu_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "da", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, da));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "line_color_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, line_color_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "line_thickness_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, line_thickness_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "line_curve_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, line_curve_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "line_curve_reverse_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, line_curve_reverse_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "line_straight_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, line_straight_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "close_path_button", FALSE, G_STRUCT_OFFSET (DotMatrixMainWindow, close_path_button));
#line 63 "../src/MainWindow.vala"
	_tmp0_ = gee_hash_multi_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 63 "../src/MainWindow.vala"
	dot_matrix_main_window_action_accelerators = (GeeMultiMap*) _tmp0_;
#line 1514 "MainWindow.c"
}

static void
dot_matrix_main_window_instance_init (DotMatrixMainWindow * self,
                                      gpointer klass)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
#line 21 "../src/MainWindow.vala"
	self->priv = dot_matrix_main_window_get_instance_private (self);
#line 49 "../src/MainWindow.vala"
	_tmp0_ = g_strdup ("#EEEEEE");
#line 49 "../src/MainWindow.vala"
	self->background = _tmp0_;
#line 50 "../src/MainWindow.vala"
	_tmp1_ = g_strdup ("#000000");
#line 50 "../src/MainWindow.vala"
	self->f_high = _tmp1_;
#line 51 "../src/MainWindow.vala"
	_tmp2_ = g_strdup ("#999999");
#line 51 "../src/MainWindow.vala"
	self->f_med = _tmp2_;
#line 52 "../src/MainWindow.vala"
	_tmp3_ = g_strdup ("#CCCCCC");
#line 52 "../src/MainWindow.vala"
	self->f_low = _tmp3_;
#line 53 "../src/MainWindow.vala"
	_tmp4_ = g_strdup ("#000000");
#line 53 "../src/MainWindow.vala"
	self->f_inv = _tmp4_;
#line 54 "../src/MainWindow.vala"
	_tmp5_ = g_strdup ("#000000");
#line 54 "../src/MainWindow.vala"
	self->b_high = _tmp5_;
#line 55 "../src/MainWindow.vala"
	_tmp6_ = g_strdup ("#888888");
#line 55 "../src/MainWindow.vala"
	self->b_med = _tmp6_;
#line 56 "../src/MainWindow.vala"
	_tmp7_ = g_strdup ("#AAAAAA");
#line 56 "../src/MainWindow.vala"
	self->b_low = _tmp7_;
#line 57 "../src/MainWindow.vala"
	_tmp8_ = g_strdup ("#FFB545");
#line 57 "../src/MainWindow.vala"
	self->b_inv = _tmp8_;
#line 21 "../src/MainWindow.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 1570 "MainWindow.c"
}

static void
dot_matrix_main_window_finalize (GObject * obj)
{
	DotMatrixMainWindow * self;
#line 21 "../src/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindow);
#line 23 "../src/MainWindow.vala"
	_dot_matrix_widgets_ui_unref0 (self->ui);
#line 49 "../src/MainWindow.vala"
	_g_free0 (self->background);
#line 50 "../src/MainWindow.vala"
	_g_free0 (self->f_high);
#line 51 "../src/MainWindow.vala"
	_g_free0 (self->f_med);
#line 52 "../src/MainWindow.vala"
	_g_free0 (self->f_low);
#line 53 "../src/MainWindow.vala"
	_g_free0 (self->f_inv);
#line 54 "../src/MainWindow.vala"
	_g_free0 (self->b_high);
#line 55 "../src/MainWindow.vala"
	_g_free0 (self->b_med);
#line 56 "../src/MainWindow.vala"
	_g_free0 (self->b_low);
#line 57 "../src/MainWindow.vala"
	_g_free0 (self->b_inv);
#line 59 "../src/MainWindow.vala"
	_g_object_unref0 (self->priv->_actions);
#line 70 "../src/MainWindow.vala"
	_g_object_unref0 (self->priv->_app);
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (dot_matrix_main_window_parent_class)->finalize (obj);
#line 1605 "MainWindow.c"
}

static GType
dot_matrix_main_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (DotMatrixMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dot_matrix_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DotMatrixMainWindow), 0, (GInstanceInitFunc) dot_matrix_main_window_instance_init, NULL };
	GType dot_matrix_main_window_type_id;
	dot_matrix_main_window_type_id = g_type_register_static (adw_application_window_get_type (), "DotMatrixMainWindow", &g_define_type_info, 0);
	DotMatrixMainWindow_private_offset = g_type_add_instance_private (dot_matrix_main_window_type_id, sizeof (DotMatrixMainWindowPrivate));
	return dot_matrix_main_window_type_id;
}

GType
dot_matrix_main_window_get_type (void)
{
	static volatile gsize dot_matrix_main_window_type_id__volatile = 0;
	if (g_once_init_enter (&dot_matrix_main_window_type_id__volatile)) {
		GType dot_matrix_main_window_type_id;
		dot_matrix_main_window_type_id = dot_matrix_main_window_get_type_once ();
		g_once_init_leave (&dot_matrix_main_window_type_id__volatile, dot_matrix_main_window_type_id);
	}
	return dot_matrix_main_window_type_id__volatile;
}

static void
_vala_dot_matrix_main_window_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec)
{
	DotMatrixMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindow);
#line 21 "../src/MainWindow.vala"
	switch (property_id) {
#line 21 "../src/MainWindow.vala"
		case DOT_MATRIX_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 21 "../src/MainWindow.vala"
		g_value_set_object (value, dot_matrix_main_window_get_actions (self));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case DOT_MATRIX_MAIN_WINDOW_APP_PROPERTY:
#line 21 "../src/MainWindow.vala"
		g_value_set_object (value, dot_matrix_main_window_get_app (self));
#line 21 "../src/MainWindow.vala"
		break;
#line 1652 "MainWindow.c"
		default:
#line 21 "../src/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/MainWindow.vala"
		break;
#line 1658 "MainWindow.c"
	}
}

static void
_vala_dot_matrix_main_window_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec)
{
	DotMatrixMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DOT_MATRIX_TYPE_MAIN_WINDOW, DotMatrixMainWindow);
#line 21 "../src/MainWindow.vala"
	switch (property_id) {
#line 21 "../src/MainWindow.vala"
		case DOT_MATRIX_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 21 "../src/MainWindow.vala"
		dot_matrix_main_window_set_actions (self, g_value_get_object (value));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case DOT_MATRIX_MAIN_WINDOW_APP_PROPERTY:
#line 21 "../src/MainWindow.vala"
		dot_matrix_main_window_set_app (self, g_value_get_object (value));
#line 21 "../src/MainWindow.vala"
		break;
#line 1684 "MainWindow.c"
		default:
#line 21 "../src/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/MainWindow.vala"
		break;
#line 1690 "MainWindow.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

